# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RANDOM STUFF
description: Photography // Food // Blog

# Build settings
markdown: kramdown

port: 9000

sass:
  sass_dir: assets/css
  style: :nested

exclude: ['Guardfile']